# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('value', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=90, null=True)),
                ('description', models.CharField(blank=True, max_length=90, null=True)),
                ('movie_image', models.ImageField(upload_to=b'media/images/movies/')),
                ('duration', models.IntegerField(default=0)),
                ('release_date', models.DateField(blank=True, default=None, null=True)),
                ('category', models.ManyToManyField(to='Data.Category')),
            ],
        ),
    ]
